### PR TITLE
25 cluster verbs

### PR DESCRIPTION
**Pull request by sgrieve**
Adding the behaviour described in #25 regarding the API action verbs.

Most of the code is written but a lot of tests are still to be added. As a minimum, before considering a merge, we need to test:

- [x] `job_information_manager.bulk_patch()`
- [x] `job_information_manager.transfer_files()`
- [x] `job_information_manager.run_action_script()`
~~- [ ] `SetupApi.post()`~~
~~- [ ] `ProgressApi.post()`~~
~~- [ ] `RunApi.post()`~~
~~- [ ] `CancelApi.post()`~~

The last 4 methods are just wrappers around code that is already tested.

### CODE REVIEW

**Comment by sgrieve** [comment]
Tests are failing on appveyor due to platform differences between windows and linux path separators. I'll figure out a solution on Monday.

**Comment by martintoreilly** [comment]
Review comments:

### Structure
- **inputs:** I think you are using `inputs` differently from its intended purpose. In the Job schema, it is another list of `source_uri` / `destination_path` tuples representing input files to the simulator (e.g. mesh / geometry files). You seem to be using it as a second set of parameters, retrieving  the value of `simulation_root` from it. This feels like a parameter specific to a certain class of JIMs. Perhaps the best place for it would be in the same config we get the SSH parameters from. I'd suggest we pass in a `config` variable to the `JIM` constructor that contains these parameters (rather than directly read the instance config file as we do currently for the SSH parameters). We should structure the config object so that we can simply pass in the Flask App config object in the app itself and construct a config with just the JIM parameters for testing (the Flask config object will incorporate the instance config as a delta on the more generic config files).
- **run:** I think we should ensure that any changes to the Job data (parameters or files) are applied prior to running a job and think we should not require the client to explicitly call `setup` to do this. I accept that there is an argument for separating out long running setup steps (e.g. long-running compilation), so am open to suggestions about how best to split functionality between `run` and `setup`. Perhaps we could have an internal `configure` function that ensures any and all changes to Job data are applied but avoids any more heavyweight setup that is independent of the Job data? For Blue, I think `setup` would just call `configure`.

### Naming
- I think we should rename `bulk_patch` to `patch_all_templates` to be more explicitly clear about what the function does.
- For consistency I'd then also rename `transfer_files` to `transfer_all_files`.

**Comment by martintoreilly** [comment]
In terms of the structure of the JIM, the replication of Job fields seems unwieldy. I'd suggest we either assign the job as a field of the JIM, or a "jobless" JIM to a field of the Job. However, issue #22 (move to SQLAlchemy) makes breaking changes to the representation of a Job, so we should save anby refactoring in this area until after we've merged this PR and the issue #22 branch into master.

**Comment by sgrieve** [comment]
>>- **run:** I think we should ensure that any changes to the Job data (parameters or files) are applied prior to running a job and think we should not require the client to explicitly call `setup` to do this. I accept that there is an argument for separating out long running setup steps (e.g. long-running compilation), so am open to suggestions about how best to split functionality between `run` and `setup`. Perhaps we could have an internal `configure` function that ensures any and all changes to Job data are applied but avoids any more heavyweight setup that is independent of the Job data? For Blue, I think `setup` would just call `configure`.

So is the best solution to add in an additional verb `CONFIGURE` which separates the patching and the transferring of files from the running of the `setup.sh` script? With the new verb it should be easy for the frontend to call the required verb prior to running a job.

**Comment by martintoreilly** [comment]
My thinking was not to have a client-facing `CONFIGURE` verb. I think that the user expectation is that if they make changes to the Job configuration in the UI and press `RUN` that the changed parameters will be in effect when the job runs. I don't see the value in requiring the user to press a button to do this. Also, I really don't think we should allow a situation where the UI shows a different Job configuration to that in effect and I think reverting the UI to the previous Job configuration if the user hasn't pressed `CONFIGURE` would be a disruptive UI journey.

**Comment by martintoreilly** [comment]
Sorry for the piecemeal nature of my comments.

The `VerbApi` methods should do a bit more, such as returning an error response if a Job doesn't exist or if the mapped JIM method returns an error. If we accept Job data for `SETUP` and `RUN` then we'll also need to validate this data. I think we should also have tests for these methods.

**Comment by sgrieve** [comment]
> My thinking was not to have a client-facing CONFIGURE verb. I think that the user expectation is that if they make changes to the Job configuration in the UI and press RUN that the changed parameters will be in effect when the job runs. I don't see the value in requiring the user to press a button to do this. Also, I really don't think we should allow a situation where the UI shows a different Job configuration to that in effect and I think reverting the UI to the previous Job configuration if the user hasn't pressed CONFIGURE would be a disruptive UI journey.

>EDIT: Looking at api.py, this means we should really be passing a Job rather than a Job ID to SETUP and RUN.

Just trying to get my head around this. We want to call `RUN` with the full job JSON created by the UI and test if it is the same as the job with the same ID in the job repository. If it is the same, carry on as normal and call the run script. If it is not the same, we need to update the contents of the job_repository and then run the patching and transferring code currently called by `SETUP`, but not run the `setup.sh` script. The finally the run script can be executed.

**Comment by sgrieve** [comment]
I agree that `simulation_root` shouldn't be in the `inputs` section of the job JSON. I will move it into the `instance/config.py` file for now, and fix what that breaks but will hold off on doing any other changes to the various config files, as I have been looking at the code in the branch addressing #22 it seems that there have been a lot of changes to what and how config files are being used and I don't want to cause further merge conflicts. I think this is something we can address in person tomorrow morning.

**Comment by martintoreilly** [comment]
> Just trying to get my head around this. We want to call RUN with the full job JSON created by the UI and test if it is the same as the job with the same ID in the job repository. If it is the same, carry on as normal and call the run script. If it is not the same, we need to update the contents of the job_repository and then run the patching and transferring code currently called by SETUP, but not run the setup.sh script. The finally the run script can be executed.

The more I think about this, the more I struggle to see how we can universally guarantee that the outcome of running `setup.sh` won't be dependent on some user-configurable property of the Job data (e.g. user configurable scripts or input files). Let's err on the side of caution for now and just insert a call to `JIM.setup()` in `JIM.run()`. When we get an example of a simulator / backend / case where there is a clearly separable one-off time consuming setup, we can look at refactoring then.

In terms of updating the Job data, we want to do what `JobApi.patch()` does. I think we've some architecture decisions to make about how we want to define this functionality once for re-use (e.g. make HTTP requests or call internally), so do the easiest of the following and we can refactor later if required:

**Comment by sgrieve** [comment]
I have found a bug in the transfer files method. It does not transfer the temporary patched file, will fix this next.

Also need to update tests for run and setup api changes and then ready to merge.

**Comment by masonlr** [comment]
This is more a note to self prior to the upcoming merging the SQL API changes. 

Prior to adding this current cluster verbs feature `JobApi.post()` was used for an all-in-one job patching/transfer/run endpoint. After adding the cluster verbs feature `JobApi.post()` is effectively duplicating the functionality of `JobApi.patch()`.

Long term we need to decide on (at least be clear on) retaining both the post and patch methods.

**Comment by martintoreilly** [comment]
It's actually `JobsApi.post()` that creates a new job (it's the collection endpoint, which is called by POSTing Job JSON to /api/jobs/` (note the lack of Job ID in the URL).

It's `JobApi.put()` that does a full replacement of a Job with the one supplied.

**Comment by masonlr** [comment]
@martintoreilly yes, hence we could remove `JobApi.post()` completely.

**Comment by martintoreilly** [comment]
The Job/Jobs API handlers are designed to implement a standard mapping between the logical CRUD (Create, Read, Update, Delete) verbs to manage Job entities directly and the corresponding HTTP verbs. The mapping is:
- **Create:** POST Job JSON with no ID to collections endpoint (`/api/jobs/`)
- **Read:** GET with empty request to entity endpoint (`/api/jobs/<job_id>/`)
- **Update:** Replace Job with full Job JSON via PUT to entity endpoint, update Job from merge patch JSON via PATCH to entity endpoint. Note that some implementations will create an entity if there is not an one with the ID the PUT request is made to, but we do not.
- **Delete:** DELETE with empty request to entity endpoint.

**Comment by martintoreilly** [comment]
Agreed we will remove `JobApi.post()` as part of the merge (I'm 3/4 of the way through it at the moment).

**Pull request merged**
