### PR TITLE
CasesAPI implementation

### PR DESCRIPTION
**Pull request by sgrieve**
Rewriting the templateApi into two separate get methods, one to return the list of cases and another to return a requested case.

Minimal tests are in place, but will need fleshed out once the final format and structure of the files has been confirmed.

Still to do:

- [x] `cases_path ` is currently hard coded into the 2 methods. This needs to be set in the app config somewhere.

- [x] I think we could also address #31  here, as we are doing a lot of API work and config work already in this PR.

- [x] Finish tests, especially once `cases_path` is moved into the app config

### CODE REVIEW

**Comment by martintoreilly** [comment]
I think the case and job APIs should be in separate files, but don't worry about it before we get the frontend and middleware integrated. We can look at this when we pause for refactoring.

**Comment by sgrieve** [comment]
Finished this PR, unless we want to refactor the 2 apis into separate files urgently.

**Comment by martintoreilly** [comment]
@sgrieve The collection (`/api/case/`) and instance (`/api/case/<case_id>`) endpoints are both returning Case summary data as per the case summary JSON example. Full Case JSON from the instance endpoint should include all the fields a Job for that Case should have, with default values. I realise this wasn't clear from the various exchanges on this last week so apologies for that.

For now, let's just rename `Blue.json` to `Blue_case_summaries.json` and add a `Blue_cases.json` with full Job JSON (minus the `id` field) for each case, providing the two different filepaths as config parameters for instantiating the APIs. We don't yet know the actual parameter sets or defaults for the real cases yet, so we should just make the two cases different in terms of user-configurable parameters. @masonlr is here today, so I can make these changes with his input sometime in the next 30-45 minutes.

**Comment by martintoreilly** [comment]
The temporary renaming of the real cases file in `TestCasesApi.test_get_cases_missing_cases_file` and `TestCaseApi.test_get_case_missing_case_file` is a bit dodgy, as a failed test might leave the name changed. However, this will only be around until we have a Case repo so I'm ok leaving it as is for now.

**Comment by martintoreilly** [comment]
I've updated the following:
- Pluralised `/api/job/` to `/api/jobs` (this was very easy thanks to @sgrieve 's refactoring to pull the URI stem out to the config file).
- There are now separate JSON resource files backing:
  - The `/api/cases/` collections endpoint, which returns the contents of `blue_case_summaries.json`. The data for each case is the same structure as in the previous shared `Blue.json` file.
  - The `/api/cases/<case_id>` instance endpoint, which returns one case from the dictionary of cases in `blue_cases.json` (a dictionary keyed by case ID). The data structure for each case is the same as for a Job for that case, with the following differences:
    - `id` field is not present
    - `user`, `name`, `description` and `creation_datetime` are `null` as the Job has not yet been created

**Comment by martintoreilly** [comment]
I'm going to merge this now. If I've made any typos with the Case instance JSON, we can fix these as we find them.

**Pull request merged**
