### PR TITLE
Implementation of Job HTTP API for #13

### PR DESCRIPTION
**Pull request by martintoreilly**
Implementation of Job HTTP API. Connects to #13. 

## Implementation notes
- Job IDs will be treated as strings for URL parsing. This supports both integer and [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) Job IDs. The underlying Jobs repository should handle conversion from string to the actual type of its ID field.
- For now Job JSON is considered valid if it has an "id" field (see `middleware.job.model.py`. Once we switch to a database-backed repo, we will very likely want to have stricter validation as we will likely have a stronger binding between code Job model and database Job model.

## Job-specific operations
**Endpoint:** `/job/<string:job_id>`, handler `JobApi`
- [x] GET (READ) `/job/<job_id>`: Retrieve job specification JSON for provided job ID
  - [x] Returns `404 - Not found` if no job exists with specified ID
  - [x] Returns `200 - OK`with job JSON in message body if job exists with specified ID
- [x] PUT (UPDATE) `/job/<job_id>`: Update existing job by replacing with provided complete job JSON
  - [x] Returns  `404 - Not found` if no job ID provided in URL
  - [x] Returns  `404 - Not found` if no job exists with job ID provided in URL
  - [x] Returns `400 - Bad request` if request body is empty
  - [x] Returns `409 - Conflict` if job IDs in URL and request JSON don't match
  - [x] Returns `400 - Bad request` if body is not valid JSON
  - [x] Returns `400 - Bad request` if body JSON not valid Job JSON
  - [x] Returns `200 - OK`with updated job JSON in message body if job exists with specified ID
- [x] DELETE (DELETE) `/job/<job_id>`: Delete job specification for provided job ID
  - [x] Returns `404 - Not found` if no job exists with specified ID
  - [x] Returns `204 - No content`with empty message body if job exists with specified ID

## Generic operations
**Endpoint:** `/job`, handler `JobsApi`
- [x] POST (CREATE) `/job`: Creates new job from Job specification JSON
  - [x] Returns `400 - Bad request` if request body body is empty
  - [x] Returns `409 - Conflict` if job  with same ID already exists
  - [x] Returns `400 - Bad request` if body is not valid JSON
  - [x] Returns `400 - Bad request` if body JSON not valid Job JSON
  - [x] Returns `200 - OK`with job JSON in message body if no job exists with specified ID
- [x] GET (LIST) `/job`: Lists all existing jobs
  - [x] Returns `200 - OK`with JSON array of object representations for existing jobs in message body (i.e.. If no jobs exist then an empty list is returned).
    - Job object representation is `{"id": <job-id>, "uri": "/job/<job_id>"}`
    - We should expand the representation returned by the LIST endpoint to include useful Job properties for users to distinguish / filter / sort jobs in a list (e.g. name, case, status)

**Note:** To expose a unified endpoint URL structure, we've used `/job/` as the root, with the presence or absence of the `<job_id>` URL fragment determining which handler to route to.

## Merge notes
This PR creates a new app entry point (`middleware/app.py`). I've added notes for running and using this entrypoint. However, we should merge the `app.py` and `views.py` entry points very soon (ideally before the issue #11 work gets too far ahead).

### CODE REVIEW

**Comment by martintoreilly** [comment]
Initial PR [build failed](https://travis-ci.org/alan-turing-institute/science-gateway-middleware/builds/254542579) due to lines over 80 characters. Fixed in commit 5aa84bb.

**Comment by martintoreilly** [comment]
@sgrieve / @masonlr: I'm going to add the DELETE method and missing tests this morning, so please leave this issue for me to merge.

**Comment by sgrieve** [comment]
Ok, I'm starting to go through this PR, but I won't complete my review until the tests and DELETE method are added.

**Comment by masonlr** [comment]
To get `run.sh` working, I need to edit the import statement in `run.py`. Not sure if this is just work in progress. See below:

`from middleware.job.inmemory_repository import JobRepositoryMemory`

**Comment by martintoreilly** [comment]
I think this fully implements issue #13 now.

**Comment by martintoreilly** [comment]
Oops. I hadn't fixed the `run.py` import bug @masonlr spotted. I'm just looking at adding a test to catch this type of bug in future then will commit a fix.

**Comment by martintoreilly** [comment]
Fixed the `run.py` import bug. Was due to renaming the source file containing the in-memory Job repo definition. I had a quick try adding a test for `run.py`, but the tests didn't return (presumably due to the app server being started).

I think we're probably ok to not have a test for now, but I've opened issue #14 to look into this more when we have time. We may well decide tt leave it entirely, as the run script is purely for running the app locally. That said, we may want to figure out how to test that the files required to run on the app service are valid and correct (i.e. `web.config` and `ptvs_virtual_env_provy.py`).

@sgrieve / @masonlr I'm happy for this PR to merge if you are.

**Pull request merged**
