### PR TITLE
11 job setup functionality

### PR DESCRIPTION
**Pull request by sgrieve**
I've created this PR as I want to have a place to communicate the progress of this branch and it is covering a few issues now. It is not ready to merge yet, as there are still things to be done.

The main changes so far are a restructure of the app directories, so we now have a `config` directory which contains a series of mostly empty config files. These will be populated with settings as development progresses and allows us to have separate testing, development and production environments, see #9 for details of this. This code also covers some of the work being done for issues #11 and #15.

There are now a series of run scripts depending on what environment you want to run on your local machine. This works by setting the environment variable `APP_CONFIG_FILE` to point to the relevant config file before the app is launched.

`secrets.py` has been replaced by a `config.py` file in the ignored directory `instance/` as this is the Flask standard. But the contents remain the same for now. It will be possible to put app API keys in this file as well and any other secret stuff needed on a particular environment. Our tests and CI should run fine with this file not existing.

So our config now comes from 3 files, each inheriting from the last, in the following order:

1. `config/default.py`
2. `instance/config.py`
3. `config/APP_CONFIG_FILE`

I have also expanded the tests to monkey patch this environment variable stuff, so testing can still be run simply from `pytest`, as well as mocking the ssh stuff so we can test the new patching code without a backend being connected.

I have committed a skeleton tests file for the `job_information_manager` but this needs populated as we already know that `1 == 1` 😀

### CODE REVIEW

**Comment by sgrieve** [comment]
Famous last words that this would all work on travis.

Looks like the `instance/config.py` is still being imported, causing a failure. Should be an easy fix, but might not have time tonight, so will return to this on Monday.

**Comment by masonlr** [comment]
Great stuff @sgrieve. I'm keen to add to this a bit too. I've worked out the transfer of the remote exit status code, etc. But the main thing I'd like to add is local tests for the template file patching.

Eg. we'll already need to run `git mv middleware/resources .` to get this working properly.

Thanks

**Comment by sgrieve** [comment]
I have reconfigured travis and appveyor so that our tests no longer fail. The `travis.yml` and `appveyor.yml` files now create a blank `config.py` file in an `instance` folder, I thought this wasn't needed due to the monkey patching, but the the file is imported before the patch is applied, so this seems like the best solution.

**Comment by masonlr** [comment]
@sgrieve I seem to be breaking all of your nice new tests and flake8 checks, sorry! Will fix up now. Thanks for getting this working.

**Comment by sgrieve** [comment]
Cool, I'm working on mocking the `SSH_USR`, `SSH_HOSTNAME` and `SSH_PORT` parameters so we can test with an empty config file. That should solve your problems, assuming the new test you wrote works locally.

**Comment by masonlr** [comment]
Hi, yes the test is working locally. I don't know whether temporary files and the `tmpdir` pytest fixture work with travis, but I'll assume they do for the moment. Thanks!

**Comment by masonlr** [comment]
Yeah, must work. [This here](http://www.camillescott.org/2016/07/15/travis-pytest-scipyconf/) is `tmpdir` in the context of travis/pytest.

**Comment by sgrieve** [comment]
I'm done with this PR until Thursday at the earliest, but all tests are passing and all my changes have been pushed. So I will pick up whatever changes have been made later in the week 🚀

**Pull request merged**
