### PR TITLE
Rough working framework

### PR DESCRIPTION
**Pull request by sgrieve**
This is a flask app that gets 2 values in a json from an authenticated http post request, processes them into a bash command, opens a connection via ssh to a server and runs the command, returning the product of the two values as the result of the initial post request.

Basic testing has been set up but one 1 test is written, but it is integrated with travis and is passing.

### CODE REVIEW

**Comment by martintoreilly** [comment]
Some comments if you're ready for them 😄 
- Will this auto-deploy to Azure successfully? I see there is a `secrets.py` file in `.gitignore` so am assuming this has some information used for authentication. If it won't autodeploy, then deployment instructions in the README would be good.
- How do we interact with the endpoint? A brief how-to in the README would be good.
- It would be nice to have Appveyor CI passing too.

**Comment by martintoreilly** [comment]
Some comments if you're ready for them 😄 

- Will the app successfully auto-deploy to the linked Azure App Service? I note there's a `secrets.py` file in `.gitignore`, which I assume has some authentication secrets in it. If the app won't auot-deploy, some instructions for manually deploying or at least building and running locally would be useful.
- How do we use the endpoint? Some instructions for this would be good.
- It would be nice if the test is passing on Appveyor as well 😄

**Comment by martintoreilly** [comment]
Has James H talked to you about potentially using [Fabric](http://www.fabfile.org/) for running remote SSH commands? It uses Paramiko under the hood, but exposes a higher level interface that can be imported by other code. I haven't looked at it much yet, but it might be worth looking at to see if it already provides the type of functionality you are writing in `ssh.py`. Fabric itself is not compatible with Python3, but there's a [Fabric3 fork](https://pypi.python.org/pypi/Fabric3) that's compatible with Python 3, while maintaining backwards compatibility with Python 2.7+.

**Comment by sgrieve** [comment]
Thanks for the comments Martin, I'll work on resolving those issues this morning. I still need to look into how we deal with a secrets file for an azure deployment.

As for fabric vs paramiko @jamespjh recommended paramiko at the end of the hack day. I thought it was because of a lack of python 3 compatibility but if that fork is stable then it might be less painful. Any thoughts James?

**Pull request merged**
